export let types = {
  media: ["mp4", "mkv", "avi", "flv", "mov"],
  archives: ["zip", "7z", "rar", "tar", "gz", "bz2"],
  document: ["docx", "doc", "pdf", "xls", "xlsx", "odt", "txt", "rtf"],
  spreadsheets: ["csv"],
  presentations: ["pptx", "ppt"],
  images: ["jpg", "jpeg", "png", "gif", "bmp", "tiff"],
  audio: ["mp3", "wav", "ogg", "flac"],
  code: ["js", "html", "css", "py", "java", "cpp", "h", "php", "rb"],
  executables: ["exe", "msi", "bat", "sh"],
  compressed: ["7z", "rar", "zip", "tar", "gz", "bz2", "xz"],
  databases: ["sqlite", "db", "sql"],
  fonts: ["ttf", "otf", "woff", "woff2"],
  presentations: ["pptx", "ppt"],
  virtualMachines: ["ova", "ovf", "vdi", "vmdk"],
  cadFiles: ["dwg", "dxf"],
  ebooks: ["epub", "mobi", "azw"],
  webFiles: ["json", "xml", "yaml", "toml"],
  certificates: ["pem", "crt", "cer"],
  subtitles: ["srt", "sub", "sbv"],
  programming: ["c", "cpp", "java", "py", "cs", "php", "js", "html", "css"],
  backup: ["bak", "bkp"],
  configuration: ["conf", "ini", "cfg"],
  logs: ["log"],
  data: ["csv", "tsv"],
  email: ["eml", "msg"],
  GISFiles: ["shp", "kml", "kmz"],
  scientificData: ["dat"],
  torrent: ["torrent"],
  Modeling: ["obj", "stl"],
  certificates: ["pfx"],
  fonts: ["ttf", "otf"],
  vectorGraphics: ["ai", "eps", "svg"],
  mindMaps: ["mm"],
  presentations: ["key"],
  virtualReality: ["vr"],
  sourceCode: ["c", "cpp", "java", "py", "cs", "php", "js", "html", "css"],
  gameFiles: ["unity3d"],
};
